xHCI: Fix the complilation error issue
Because xhci_plat_phytium220x is only defined when CONFIG_OF is
configured, but it is also used when CONFIG_OF is not configured,
which will cause the compilation to fail.

drivers/usb/host/xhci-plat.c:513:33: error: ‘xhci_plat_phytium_pe220x’
undeclared here; did you mean ‘xhci_plat_runtime_resume’?
  { PHYT0039, (kernel_ulong_t)&xhci_plat_phytium_pe220x },

so the xhci_plat_phytium220x definition is moved to out of
CONFIG_OF definiton to slove the above problem.

Mainline: Open-Source
Signed-off-by: Chen Zhenhua <chenzhenhua@phytium.com.cn>
Signed-off-by: Wang Yinfeng <wangyinfeng@phytium.com.cn>
Change-Id: I39fee1b74a25b695d58aa075dd7f25b4e088d305