pswiotlb: Fix compilation error caused by redefinition of dma_get_min_align_mask
In file included from arch/arm64/mm/dma-mapping.c:17:
./include/linux/pswiotlb.h:79:28: error: redefinition of ‘dma_get_min_align_mask’
   79 | static inline unsigned int dma_get_min_align_mask(struct device *dev)
      |                            ^~~~~~~~~~~~~~~~~~~~~~

Signed-off-by: zuoqian <zuoqian2032@phytium.com.cn>