net/phytmac: Fix compilation errors caused by disabling CONFIG_ACPI
Disabling CONFIG_ACPI will cause errors like 'error: implicit
declaration of function ‘acpi_evaluate_integer’, so it is necessary
to add #ifdef CONFIG_ACPI for protection.

Mainline: Open-Source
Signed-off-by: Li Tongfeng <litongfeng1497@phytium.com.cn>
Signed-off-by: Wang Yinfeng <wangyinfeng@phytium.com.cn>
Change-Id: I3c7a7bd856d51b67e60a087392a806a5fbfd623d